### PR TITLE
Porting minGPT to Hydra

### PR DESCRIPTION
**Pull request by omry**
This PR is porting minGPT to [Hydra](https://hydra.cc).
In an nutshell, you can override everything from the command line.
You can use composition to alternate between whole nodes of your config (in this example model, dataset and trainer are all pluggable).

Hydra has it's own plugins for launching all Hydra applications to various environments (think launching to SLURM without writing extra scripts), and to do Hyper parameter optimization (think optimizing with Ax or Nevergrad without changing your code), or just doing simple grid search (--multirun) to find the best model/dataset combination for example.

This example also uses `Stuctured Configs`, which are a way to get type safe config that is validated both statically (duck typing) and at runtime. try to override a parameter to a wrong type to see what I mean.
The config structure is all in `mingpt/conf/__init__.py` in the PR. take a look.

This example demonstrate what I currently consider best practices for Hydra 1.0.0rc3 (released today), but Hydra is very flexible and you can change many things.

There is a whole lot more to Hydra, the best way to learn about it is to go through the website tutorials.

```yaml
$ python mingpt/main.py                                                                                                                                                                                                                                                                                                                                   
train_dataset:                                                        
  _target_: mingpt.chardataset.CharDataset                                                                                                                                                                                                                                                                                                                                           
  url: https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
  filename: tinyshakespeare.txt                                                                                                                                                                                                                                                                                                                                                      
  block_size: 128                                                     
  cache_dir: ${hydra:runtime.cwd}/datasets_cache                                                                                                                                                                                                                                                                                                                                     
test_dataset: null                                                    
model:                                                                                                                                                                                                                                                                                                                                                                               
  _target_: mingpt.model.GPT                                          
  config:                                                                                                                                                                                                                                                                                                                                                                            
    embd_pdrop: 0.1    
    resid_pdrop: 0.1                               
    attn_pdrop: 0.1                                      
    n_layer: 8                     
    n_head: 8                                                                                
    n_embd: 512                                          
    block_size: ${train_dataset.block_size}
    vocab_size: ???                                                                                                                                                                                                                                                                                                                                                                  
seed: 42                                                                                                              
trainer:                                                                                                                                                                                                                                                                                                                                                                             
  _target_: mingpt.trainer.Trainer                                                
  config:                                                                                                                                                                                                                                                                                                                                                                            
    max_epochs: 200                                                                                                                                                                                                                                                                                                                                                                  
    batch_size: 512                                                                                                                                                                                                                                                                                                                                                                  
    learning_rate: 0.0006                                             
    betas:                                                                                                                                                                                                                                                                                                                                                                           
    - 0.9                                                                                                                                                                                                                                                                                                                                                                            
    - 0.95                                                                                                                                                                                                                                                                                                                                                                           
    grad_norm_clip: 1.0                                                                                                                                                                                                                                                                                                                                                              
    weight_decay: 0.1                                                                                                                                                                                                                                                                                                                                                                
    lr_decay: true
    warmup_tokens: 10240
    final_tokens: ???
    ckpt_path: checkpoint.t7
    num_workers: 4

[2020-08-17 16:27:51,115][mingpt.chardataset][INFO] - Loading /home/omry/dev/minGPT/datasets_cache/tinyshakespeare.txt
[2020-08-17 16:27:51,124][mingpt.chardataset][INFO] - data has 1115394 characters, 65 unique.
[2020-08-17 16:27:51,436][mingpt.model][INFO] - number of parameters: 2.535219e+07
[2020-08-17 16:27:51,524][mingpt.trainer][INFO] - Using device : 0
  0%|                                                                                                                                                                                                                                                                                                                                                         | 0/17 [00:00<?, ?it/s]
/home/omry/miniconda3/envs/mingpt/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
epoch 1 iter 16: train loss 3.34601. lr 5.999637e-04: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:16<00:00,  1.04it/s]
[2020-08-17 16:28:09,451][mingpt.trainer][INFO] - saving checkpoint.t7
```

### CODE REVIEW

**Comment by omry** [comment]
After playing with this a bit I realized my main is using the evaluation code from the readme which is outdated.
I tried adding model checkpointing and loading but ran into some issues (my PyTorch is a bit rusty).

I am pretty sure this will be helpful as is, but I am happy to polish it some more after a bit of feedback.

**Comment by karpathy** [comment]
Whoa. I certainly won't be able to merge this because it would violate the "min" in minGPT, but it's fun to see!

**Comment by omry** [comment]
Yeah, I thought it might be the case :).

Hydra can definitely work for simple use case, but if you have a requirement to not have dependencies for this project, then at least I hope you give this a shot and try it for the next more serious project.

By the way, if the objection is the config yaml config files I can make it work purely with Structured Configs (which are not much more than dataclasses).

**Comment by karpathy** [comment]
Will take a look, thank you! Filing under "won't merge" and closing.

**Pull request closed without merging**
