### PR TITLE
If possible, please add TQDM (auto)

### PR DESCRIPTION
**Pull request by asigalov61**
Here is a simple change that adds a nice TQDM progress bar to the code. It should be auto for best compatibility with Jupyter Notebooks AFAIK.

Please add this change as I think it will be very nice and appealing to users.

Thank you.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@asigalov61 what effect does tqdm.auto.tqdm() have vs tqdm.tqdm()?

**Comment by asigalov61** [comment]
@glenn-jocher I think tqdm.auto automatically adjusts to the environment it is working at. tqdm.tqdm does not always work right/well in Jupyter notebooks from my experience, so the TQDM docs recommend to use tqdm.auto

You are welcome to double-check the docs/recommendations if you like because I may be misunderstanding something...

Thank you.

**Comment by glenn-jocher** [comment]
@asigalov61 I see, thanks for the info! I was asking because I use tqdm abundantly in my YOLOv5 repo. I suppose a good code-agnostic import might simply be to replace our existing instances of `from tqdm import tqdm` to from `tqdm.auto import tqdm`. 

I wonder why if this helps cross-platform robustness they did not include it as the default? Will check the docs.

**Comment by asigalov61** [comment]
@glenn-jocher Thank you so much, Glenn. That will be much appreciated. You guys did a great job with minGPT. I am using it in one of my notebooks for Music AI experimentation/purposes 👍 

I think they still working on the Jupyter/Notebooks integration (I think it is still kinda experimental but it is working at least on my end).

Here is what the docs say to save you time:

```
class tqdm.notebook.tqdm(tqdm.tqdm):
    """Experimental IPython/Jupyter Notebook widget."""

def tqdm.notebook.trange(*args, **tqdm_kwargs):
    """Experimental IPython/Jupyter Notebook widget version of `trange`."""

class tqdm.auto.tqdm(tqdm.tqdm):
    """Automatically chooses beween `tqdm.notebook` and `tqdm.tqdm`."""
```

https://github.com/tqdm/tqdm#ipython-jupyter-integration

**Comment by karpathy** [comment]
PR contains some additional changes (the lr decay). I probably won't merge this but ty for the PR

**Pull request closed without merging**
